# Generated by Django 3.1.7 on 2021-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=100)),
                ('enrollmentno', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(blank=True)),
                ('studentimage', models.ImageField(upload_to='')),
                ('dept', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'studentreg',
            },
        ),
        migrations.AlterField(
            model_name='facultyreg',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyreg',
            name='lname',
            field=models.CharField(max_length=100),
        ),
    ]
