# Generated by Django 3.1.7 on 2021-05-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('present_date', models.DateField()),
                ('present_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='reports',
        ),
    ]
