# Generated by Django 3.1.7 on 2021-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20210511_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='mon_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sroll', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('present_date', models.DateField()),
                ('present_time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('curmonth', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='s_reports',
        ),
    ]
